// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-crop-predictions.ts
import { createClient } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_crop_predictions_default = defineTool({
  name: "list_crop_predictions",
  title: "List crop predictions",
  description: "List the signed-in user's saved crop yield predictions.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max predictions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("crop_predictions").select("crop_type, predicted_yield, area_hectares, season, state, district, rainfall_mm, soil_type, confidence_score, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { predictions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-farm-finances.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_farm_finances_default = defineTool2({
  name: "list_farm_finances",
  title: "List farm finances",
  description: "List the signed-in user's farm finance records (expenses, expected revenue, profit/loss).",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(10).describe("Max records to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("farm_finances").select("crop_type, total_expense, expected_revenue, net_profit_loss, predicted_yield, predicted_price, updated_at").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { finances: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-mandi-prices.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.53.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_mandi_prices_default = defineTool3({
  name: "get_mandi_prices",
  title: "Get mandi prices",
  description: "Fetch latest Indian mandi (market) prices, optionally filtered by commodity or state.",
  inputSchema: {
    commodity: z3.string().trim().min(1).optional().describe("Optional commodity filter, e.g. 'Rice'."),
    state: z3.string().trim().min(1).optional().describe("Optional state filter, e.g. 'Telangana'."),
    limit: z3.number().int().min(1).max(50).default(20).describe("Max rows to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ commodity, state, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser3(ctx).from("mandi_prices").select("commodity, market, state, min_price, max_price, modal_price, arrival_date").order("arrival_date", { ascending: false }).limit(limit);
    if (commodity) query = query.ilike("commodity", `%${commodity}%`);
    if (state) query = query.ilike("state", `%${state}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { prices: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xllpedrhhzoljkfvkgef";
var mcp_default = defineMcp({
  name: "agrosight-mcp",
  title: "AgroSight MCP",
  version: "0.1.0",
  instructions: "AgroSight tools for Indian farmers. Read the signed-in user's saved crop yield predictions, farm finance records, and the latest mandi (market) prices.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_crop_predictions_default, list_farm_finances_default, get_mandi_prices_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
